"""Initial Migration

Revision ID: 2ecb10230bfd
Revises: 9bfe0d630b5f
Create Date: 2019-03-02 19:53:07.746950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ecb10230bfd'
down_revision = '9bfe0d630b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('pitch_content', sa.String(length=255), nullable=True))
    op.add_column('pitch', sa.Column('pitch_title', sa.String(length=255), nullable=True))
    op.drop_column('pitch', 'pitch')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('pitch', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('pitch', 'pitch_title')
    op.drop_column('pitch', 'pitch_content')
    # ### end Alembic commands ###
